// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTbRvJR8EgRFBfrZCm7sc6QsC3IG3v52g',
    appId: '1:254273909500:web:bd18dd6a0e709ed3ac5d79',
    messagingSenderId: '254273909500',
    projectId: 'chat-1917f',
    authDomain: 'chat-1917f.firebaseapp.com',
    storageBucket: 'chat-1917f.appspot.com',
    measurementId: 'G-X0NVM3JT81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6omfPQrnBgAO2soQbn8-u_1EqY9QM-d4',
    appId: '1:254273909500:android:6d75b309260c2f22ac5d79',
    messagingSenderId: '254273909500',
    projectId: 'chat-1917f',
    storageBucket: 'chat-1917f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtEp3GOzxPxo8eXluuo27ZAigObkojzis',
    appId: '1:254273909500:ios:2fba84bac5a94db8ac5d79',
    messagingSenderId: '254273909500',
    projectId: 'chat-1917f',
    storageBucket: 'chat-1917f.appspot.com',
    iosBundleId: 'com.example.chat',
  );
}
